# Configuration for https://travis-ci.org/

language: go
go_import_path: blitiri.com.ar/go/remoteu2f
dist: bionic

addons:
    apt:
        packages:
            - libpam0g-dev  # for our PAM library

go:
    - stable

script:
    - make all

